# Generated by Django 3.1.3 on 2020-11-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
